/* eslint-disable @remotion/deterministic-randomness */
import { getOrientationConfig } from "../../components/utils";
import { logger } from "../../logger";
import { OrientationEnum, type Video } from "../../types/shorts";

const defaultTimeoutMs = 30000; // Veo takes longer to generate
const retryTimes = 3;
const maxGenerationTimeMs = 120000; // 2 minutes max wait

export class GoogleVeoAPI {
  private baseURL: string;
  private projectId: string;
  private region: string = "us-central1";
  private accessToken: string | null = null;
  
  constructor(
    private API_KEY_PATH: string, // Path to service account JSON file
    projectId: string, 
    region: string = "us-central1"
  ) {
    this.projectId = projectId;
    this.region = region;
    this.baseURL = `https://${region}-aiplatform.googleapis.com/v1/projects/${projectId}/locations/${region}/publishers/google/models`;
  }
  
  private async getAccessToken(): Promise<string> {
    // Use Google Cloud SDK or service account key to get access token
    try {
      const { GoogleAuth } = await import('google-auth-library');
      const auth = new GoogleAuth({
        keyFilename: this.API_KEY_PATH,
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
      });
      const client = await auth.getClient();
      const accessToken = await client.getAccessToken();
      
      if (!accessToken.token) {
        throw new Error("Failed to get access token");
      }
      
      this.accessToken = accessToken.token;
      return accessToken.token;
    } catch (error) {
      logger.error(error, "Failed to authenticate with Google Cloud");
      throw new Error(`Google Cloud authentication failed: ${error}`);
    }
  }

  private async _generateVideo(
    prompt: string,
    minDurationSeconds: number,
    orientation: OrientationEnum,
    timeout: number = defaultTimeoutMs,
  ): Promise<Video> {
    // Get access token for authentication
    const accessToken = await this.getAccessToken();
    
    logger.debug(
      { prompt, minDurationSeconds, orientation },
      "Generating video with Google Veo 3 Fast API",
    );

    const aspectRatio = orientation === OrientationEnum.portrait ? "9:16" : "16:9";
    // Veo 3 Fast supports 4, 6, or 8 seconds
    const duration = minDurationSeconds <= 4 ? 4 : minDurationSeconds <= 6 ? 6 : 8;

    const headers = new Headers();
    headers.append("Authorization", `Bearer ${accessToken}`);
    headers.append("Content-Type", "application/json");

    // Use Veo 3 Fast model for rapid generation
    const modelEndpoint = `${this.baseURL}/veo-3.0-fast-generate-preview:predict`;
    
    const requestBody = {
      instances: [{
        prompt: prompt
      }],
      parameters: {
        durationSeconds: duration,
        aspectRatio: aspectRatio,
        resolution: "1080p", // HD quality
        sampleCount: 1,
        generateAudio: true, // Enable synchronized sound
        storageUri: "" // Leave empty for direct response
      }
    };

    logger.debug({ requestBody }, "Sending request to Veo API");

    try {
      const response = await fetch(modelEndpoint, {
        method: "POST",
        headers,
        body: JSON.stringify(requestBody),
        signal: AbortSignal.timeout(timeout),
      });

      if (!response.ok) {
        if (response.status === 401) {
          throw new Error(
            "Invalid Google Cloud API key - please make sure you have proper authentication set up"
          );
        }
        if (response.status === 403) {
          throw new Error(
            "Google Cloud Vertex AI access denied - please enable Vertex AI API and check permissions"
          );
        }
        const errorText = await response.text();
        throw new Error(`Veo API error: ${response.status} ${response.statusText} - ${errorText}`);
      }

      const result = await response.json();
      logger.debug({ result }, "Received response from Veo API");

      // Extract video URL from response
      if (!result.predictions || !result.predictions[0]) {
        throw new Error("No video generated by Veo API");
      }

      const prediction = result.predictions[0];
      
      // Veo returns video data differently - check for video URI
      let videoUrl: string | undefined;
      let videoId: string = `veo-${Date.now()}`;

      if (prediction.gcsOutputUri) {
        videoUrl = prediction.gcsOutputUri;
      } else if (prediction.videoUri) {
        videoUrl = prediction.videoUri;
      } else if (prediction.outputUri) {
        videoUrl = prediction.outputUri;
      }

      if (!videoUrl) {
        throw new Error("No video URL found in Veo API response");
      }

      const { width: requiredVideoWidth, height: requiredVideoHeight } =
        getOrientationConfig(orientation);

      const video: Video = {
        id: videoId,
        url: videoUrl,
        width: requiredVideoWidth,
        height: requiredVideoHeight,
      };

      logger.debug(
        { prompt, video, minDurationSeconds, orientation },
        "Generated video with Google Veo API",
      );

      return video;

    } catch (error: unknown) {
      logger.error(error, "Error generating video with Veo API");
      throw error;
    }
  }

  async findVideo(
    searchTerms: string[],
    minDurationSeconds: number,
    excludeIds: string[] = [],
    orientation: OrientationEnum = OrientationEnum.portrait,
    timeout: number = defaultTimeoutMs,
    retryCounter: number = 0,
  ): Promise<Video> {
    // Create a comprehensive prompt from search terms
    const prompt = this.createVideoPrompt(searchTerms, minDurationSeconds, orientation);
    
    try {
      const video = await this._generateVideo(
        prompt,
        minDurationSeconds,
        orientation,
        timeout,
      );

      // Check if this video ID should be excluded (unlikely with generated content, but keeping interface)
      if (excludeIds.includes(video.id)) {
        // Generate with a slightly modified prompt
        const modifiedPrompt = this.createVideoPrompt(searchTerms, minDurationSeconds, orientation, true);
        return await this._generateVideo(modifiedPrompt, minDurationSeconds, orientation, timeout);
      }

      return video;

    } catch (error: unknown) {
      if (
        error instanceof Error &&
        error instanceof DOMException &&
        error.name === "TimeoutError"
      ) {
        if (retryCounter < retryTimes) {
          logger.warn(
            { searchTerms, retryCounter },
            "Timeout error generating video, retrying...",
          );
          return await this.findVideo(
            searchTerms,
            minDurationSeconds,
            excludeIds,
            orientation,
            timeout,
            retryCounter + 1,
          );
        }
        logger.error(
          { searchTerms, retryCounter },
          "Timeout error, retry limit reached",
        );
      }

      logger.error(error, "Error finding video with Veo API");
      throw new Error(`Failed to generate video with Veo API: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  private createVideoPrompt(
    searchTerms: string[], 
    durationSeconds: number, 
    orientation: OrientationEnum,
    variant: boolean = false
  ): string {
    const baseTerms = searchTerms.join(" ");
    const orientationHint = orientation === OrientationEnum.portrait 
      ? "vertical mobile-friendly format" 
      : "cinematic widescreen format";
    
    const variantSuffix = variant ? ", alternative perspective" : "";
    
    // Create a more detailed prompt for better Veo results
    const prompt = `Create a high-quality ${durationSeconds}-second video featuring ${baseTerms}. ` +
      `The video should be in ${orientationHint}, with smooth camera movements and professional lighting. ` +
      `Include rich details, vibrant colors, and engaging composition. ` +
      `Make it suitable for social media content${variantSuffix}.`;
    
    logger.debug({ prompt, searchTerms, orientation }, "Created Veo prompt");
    
    return prompt;
  }
}